### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by daiki-mrt** [daiki-mrt/furima-31052#9]
## URL
https://furima-31052.herokuapp.com/
user: admin
pass: 0634

## 出品者
email: furi@furi
pass: a1a1a1

## 購入者
email: fu@fu
pass: a1a1a1

## テストカード
番号: 4242424242424242
期限: 3月/33年
セキュリティコード: 123

**Comment by naokihayasan127** [comment]
森田さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
非常に綺麗なサイトです！！
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
